특이값 분해(Singular Value Decomposition, SVD)**는 행렬을 세 개의 행렬로 분해하여 원래 행렬의 특성을 분석하는 방법입니다. 

SVD는 선형대수에서 중요한 역할을 하며, 특히 데이터 압축, 차원 축소, 잡음 제거 등 다양한 분야에 널리 사용됩니다.

SVD의 정의 : 특이값 분해는 다음과 같은 형태로 주어진 임의의 행렬 

𝐴를 세 행렬의 곱으로 표현하는 방법입니다:

SVD의 구성 요소

1.특이값 (Singular Values) :행렬 Σ의 대각선 요소들은 특이값입니다.
    
2.왼쪽 특이 벡터 (Columns of 𝑈) :행렬 U의 열은 원래 행렬의 행 공간(row space)*과 관련된 정보를 포함합니다.
    
3.오른쪽 특이 벡터 (Columns of 𝑉) :행렬 𝑉의 열은 열 공간(column space)*에 관한 정보를 제공합니다.

In [ ]:
# 코드 설명
# np.linalg.svd(A)는 𝐴에 대해 SVD를 수행합니다.
# 𝑈: 왼쪽 특이 벡터를 포함하는 행렬.
# Σ: 특이값을 포함하는 벡터. 대각 행렬로 만들어질 수 있습니다.
# 𝑉𝑇: 오른쪽 특이 벡터의 전치 행렬.

In [2]:
import numpy as np

# Define a sample matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform Singular Value Decomposition
U, Sigma, VT = np.linalg.svd(A)

# Display the results
print("Matrix A:")
print(A)
print("\nLeft singular vectors (U):")
print(U)
print("\nSingular values (Sigma):")
print(Sigma)
print("\nRight singular vectors (V^T):")
print(VT)


Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Left singular vectors (U):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular values (Sigma):
[9.52551809 0.51430058]

Right singular vectors (V^T):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
# 코드 설명
# 행렬 𝐴 정의:
# 3x3 행렬 𝐴를 정의합니다.
# SVD 수행:
# np.linalg.svd(A)를 통해 행렬 A를 특이값 분해합니다.
# 𝑈, Σ, 𝑉𝑇 를 구합니다.
# Σ 행렬 변환:
# Σ는 벡터로 반환되므로, 이를 풀 Σ 대각 행렬로 변환합니다.
# 출력:
# U,Σ, 𝑉𝑇 , 그리고 복원된 행렬을 출력합니다.
# np.allclose()를 통해 복원된 행렬과 원래 행렬이 유사한지 확인합니다.

In [1]:
import numpy as np

# Define a new sample matrix A (3x3 matrix)
A = np.array([[3, 1, 1],
              [-1, 3, 1],
              [1, 1, 5]])

# Perform Singular Value Decomposition
U, Sigma, VT = np.linalg.svd(A)

# Convert Sigma to a diagonal matrix
Sigma_full = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma_full, Sigma)

# Display the results
print("Matrix A:")
print(A)
print("\nLeft singular vectors (U):")
print(U)
print("\nSingular values (Sigma):")
print(Sigma)
print("\nSigma as a full diagonal matrix:")
print(Sigma_full)
print("\nRight singular vectors (V^T):")
print(VT)

# Reconstruct A using U, Sigma, and V^T
A_reconstructed = np.dot(U, np.dot(Sigma_full, VT))
print("\nReconstructed Matrix A (using U, Sigma, V^T):")
print(A_reconstructed)

# Check if the original and reconstructed matrices are close
is_reconstructed = np.allclose(A, A_reconstructed)
print("\nIs the reconstructed matrix close to the original A?:", is_reconstructed)


Matrix A:
[[ 3  1  1]
 [-1  3  1]
 [ 1  1  5]]

Left singular vectors (U):
[[-0.37120189  0.57930352 -0.72568353]
 [-0.29511116 -0.8146028  -0.49933123]
 [-0.88040818  0.02880461  0.47334104]]

Singular values (Sigma):
[5.75682289 3.16880566 2.41198278]

Sigma as a full diagonal matrix:
[[5.75682289 0.         0.        ]
 [0.         3.16880566 0.        ]
 [0.         0.         2.41198278]]

Right singular vectors (V^T):
[[-0.29511116 -0.37120189 -0.88040818]
 [ 0.8146028  -0.57930352 -0.02880461]
 [-0.49933123 -0.72568353  0.47334104]]

Reconstructed Matrix A (using U, Sigma, V^T):
[[ 3.  1.  1.]
 [-1.  3.  1.]
 [ 1.  1.  5.]]

Is the reconstructed matrix close to the original A?: True
