## 벡터와 행렬 표기

In [19]:
# 기본 라이브러리 호출하기
import numpy as np  # 선형대수학을 위한 파이썬 라이브러리
import matplotlib.pylab as plt  

In [23]:
# 벡터x  2차원 배열로
x = np.array([[1], [3], [5], [7]])
x

array([[1],
       [3],
       [5],
       [7]])

In [25]:
# 1차원 배열 객체
x1 = np.array([1, 3, 5, 7])
x1

array([1, 3, 5, 7])

In [26]:
## 행렬
# 넘파이를 이용 2차원 행렬 표기

x2 = np.array([[11,12,13],[21,22,23]])
x2

array([[11, 12, 13],
       [21, 22, 23]])

## 벡터와 행렬 사칙연산

In [1]:
# 기본 라이브러리 호출하기
import numpy as np
import matplotlib.pylab as plt

In [2]:
# 1차원 배열로 벡터를 표시
x = np.array([1, 2, 3, 4])
y = np.array([10, 11, 12, 13])

In [3]:
# 뎃셈
x + y

array([11, 13, 15, 17])

In [4]:
x - y

array([-9, -9, -9, -9])

In [5]:
y-x

array([9, 9, 9, 9])

In [ ]:
# 행렬 뎃셈

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
c = np.array([[5, 6], [7, 8]])

In [16]:
a+b

array([[11, 22],
       [33, 44]])

In [17]:
b-c

array([[ 5, 14],
       [23, 32]])

In [18]:
a+b-c

array([[ 6, 16],
       [26, 36]])

In [ ]:
# 벡터와 벡터 곱셈

In [28]:
#  곱셉을 @ 연산자로 계산
x = np.array([[1], [2], [3]])
y = np.array([[10], [20], [30]])

x.T @ y  

array([[140]])

In [29]:
#  곱셉을 np.dot
x = np.array([[1], [2], [3]])
y = np.array([[10], [20], [30]])
np.dot(x.T, y)

array([[140]])

In [ ]:
# 행렬 곱셉

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[10, 20], [30, 40], [50, 60]])
A @ B

array([[220, 280],
       [490, 640]])

In [32]:
# 행렬 교환법칙 성립하지 않는다
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[10, 20], [30, 40], [50, 60]])
B @ A

array([[ 90, 120, 150],
       [190, 260, 330],
       [290, 400, 510]])